
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Removing ubuntu image
      openstack.cloud.image:
        name: ubuntu-bionic-cloudimg
        state: absent
    - name: Removing keypair
      openstack.cloud.keypair:
        state: absent
        name: ansible_key
    - name: Removing router dashboard-router
      openstack.cloud.router:
        state: absent
        name: dashboard-router
    - name: Removing network dashboard-net
      openstack.cloud.network:
        name: dashboard-net
        state: absent
    - name: Removing subnet dashboard-subnet
      openstack.cloud.subnet:
        state: absent
        name: dashboard-subnet
    - name: Removing security group ssh-in
      openstack.cloud.security_group:
        state: absent
        name: ssh-in
    - name: Removing security group dashboard-sg
      openstack.cloud.security_group:
        state: absent
        name: dashboard-sg
