
- hosts: localhost
  tasks:
    - name: Creating ubuntu image
       openstack.cloud.image:
        name: ubuntu-bionic-cloudimg
        container_format: bare
        disk_format: qcow2
        state: present
        filename: bionic-server-cloudimg-amd64.img
    - name: Create a keypair
      openstack.cloud.keypair:
        state: present
        name: ansible_key
        public_key_file: ./ssh_key.pub
    - name: Create a new network called dashboard-net
      openstack.cloud.network:
        name: dashboard-net
    - name: Create a new subnet called dashboard-subnet
      openstack.cloud.subnet:
        state: present
        network_name: dashboard-net
        name: dashboard-subnet
        cidr: 10.1.0.0/24
        dns_nameservers:
          - 1.1.1.1
          - 1.0.0.1
    - name: Create a new security group called ssh-in
      openstack.cloud.security_group:
        state: present
        name: ssh-in
        description: security group for allowing ssh connections
    - name: Adding SSH incoming connections rule
      openstack.cloud.security_group_rule:
        security_group: ssh-in
        protocol: tcp
        port_range_min: 22
        port_range_max: 22
        remote_ip_prefix: 0.0.0.0/0
    - name: Create a new security group called dashboard-sg
      openstack.cloud.security_group:
        state: present
        name: dashboard-sg
        description: security group for dashboard service
    - name: Adding WEB incoming rule
      openstack.cloud.security_group_rule:
        security_group: dashboard-sg
        protocol: tcp
        port_range_min: 80
        port_range_max: 80
        remote_ip_prefix: 0.0.0.0/0
    - name: Adding WEB (5000) incoming rule
      openstack.cloud.security_group_rule:
        security_group: dashboard-sg
        protocol: tcp
        port_range_min: 5000
        port_range_max: 5000
        remote_ip_prefix: 0.0.0.0/0
    - name: Creating router for allowing connections between NVM and external network
      openstack.cloud.router:
        state: present
        name: dashboard-router
        network: public
        interfaces:
          - dashboard-subnet