
- name: Openstack authentication
  include: auth.yml
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Removing server
      openstack.cloud.server:
        state: absent
        name: ubuntu