- hosts: localhost
  gather_facts: no
  environment:
    OS_AUTH_URL: http://10.235.1.223/identity
    OS_PROJECT_NAME: foodapp-dashboard
    OS_USERNAME: admin
    OS_PASSWORD: password
    OS_USER_DOMAIN_NAME: Default
    OS_PROJECT_DOMAIN_ID: default
  tasks:
    - name: Removing server
      openstack.cloud.server:
        state: absent
        name: ubuntu