- hosts: localhost
  gather_facts: no
  tasks:
    - name: Openstack authentication
      include_tasks: auth.yml
    - name: Removing server
      openstack.cloud.server:
        state: absent
        name: ubuntu