
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Create a new server and connects it to the network (this may take some time)
      openstack.cloud.server:
        state: present
        name: ubuntu
        image: ubuntu-bionic-cloudimg
        key_name: ansible_key
        timeout: 200
        flavor: m1.small
        nics:
         - net-name: dashboard-net
        security_groups:
         - dashboard-sg
         - ssh-in
        meta:
         hostname: ubuntu-test
      register: my_vm
    - name: Add VM to inventory
      add_host:
        name: my_openstack_vm
        groups: openstack_vms
        ansible_host: "{{ my_vm.server.public_v4 }}"
    #- name: Pause
    #  pause:
    #    seconds: 90
    - name: Checking when the SSH server becomes available
      local_action: "wait_for port=22 host={{ my_vm.server.public_v4 }}"
- hosts: openstack_vms
  gather_facts: no
  remote_user: ubuntu
  become: true
  tasks:
    - name: Wait for connection
      wait_for_connection:

    - name: Add eval user
      user:
        name: eval
        shell: /bin/bash

    - name: Add eval key
      ansible.posix.authorized_key:
        user: eval
        state: present
        key: "{{ lookup('file', 'ssh_key.pub') }}"

    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
    - name: Install git
      apt:
        name: git
        state: present
    - name: Install curl
      apt:
        name: curl
        state: present
    - name: Download node
      command: curl -sL https://deb.nodesource.com/setup_14.x -o node_setup.sh
      args:
        chdir: /home/ubuntu
    - name: Configure node setup
      shell: bash ./node_setup.sh
      args:
        chdir: /home/ubuntu
    - name: Install node
      apt:
        name: nodejs
        state: present
    - name: Clone dashboard frontend
      git:
        repo: https://github.com/riccardogilli/foodapp-dashboard-frontend.git
        dest: /var/www/frontend
    - name: Deploy dashboard frontend
      copy:
        remote_src: yes
        src: /var/www/frontend/dist/
        dest: /var/www/html
    - name: Clone dashboard backend
      git:
        repo: https://github.com/riccardogilli/foodapp-dashboard-backend.git
        dest: /home/ubuntu/dashboard-backend
    - name: Configure dashboard backend
      copy:
        src: ./.env.backend
        dest: /home/ubuntu/dashboard-backend/.env
    - name: Running npm install for the backend
      community.general.npm:
        path: /home/ubuntu/dashboard-backend
    - name: Install pm2
      community.general.npm:
        name: pm2
        global: yes
    - name: Run dashboard backend
      command: pm2 start src/app.js --name node-backend
      args:
        chdir: /home/ubuntu/dashboard-backend